# encoding: utf-8

# Box / OS
VAGRANT_BOX = 'debian/contrib-jessie64'

# Memorable name for your
VM_NAME = 'puzzlehunt-local'

Vagrant.configure(2) do |config|

  # Vagrant box from Hashicorp
  config.vm.box = VAGRANT_BOX
  
  # Actual machine name
  config.vm.hostname = VM_NAME

  # Set VM name in Virtualbox
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.provision "shell", path: "puzzlehunt_server/config/puzzlehunt_setup.sh"

  config.vm.provision "shell", 
    inline: "/vagrant/puzzlehunt_server/venv/bin/python /vagrant/puzzlehunt_server/manage.py collectstatic --noinput --settings puzzlehunt_server.settings.local_settings -v0", 
    run: "always"
end