# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 04:15
from __future__ import unicode_literals

from django.db import migrations, models


def set_my_defaults(apps, schema_editor):
    Hunt = apps.get_model('huntserver', 'Hunt')
    for hunt in Hunt.objects.all().iterator():
        hunt.display_end_date = hunt.end_date
        hunt.display_start_date = hunt.start_date
        hunt.save()


def reverse_set_default(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0023_userproxyobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='display_end_date',
            field=models.DateTimeField(null=True, help_text=b'The end date/time displayed to users'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='display_start_date',
            field=models.DateTimeField(null=True, help_text=b'The start date/time displayed to users'),
        ),

        migrations.RunPython(set_my_defaults, reverse_set_default),

        migrations.AlterField(
            model_name='hunt',
            name='display_end_date',
            field=models.DateTimeField(help_text=b'The end date/time displayed to users'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='display_start_date',
            field=models.DateTimeField(help_text=b'The start date/time displayed to users'),
        ),
    ]
