# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0024_auto_20181021_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False),
        ),
    ]
