# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-21 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0025_puzzle_is_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False, help_text=b'Is this puzzle a meta-puzzle?'),
        ),
    ]
