# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0026_auto_20181021_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='is_html_puzzle',
            field=models.BooleanField(default=False, help_text=b"Does this puzzle use an HTML folder as it's source?"),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='resource_link',
            field=models.URLField(blank=True, help_text=b'The full link (needs http://) to a folder of additional resources.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='link',
            field=models.URLField(blank=True, help_text=b'The full link (needs http://) to a publicly accessible PDF of the puzzle'),
        ),
    ]
