# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-04 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0027_auto_20181023_2303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_name', models.CharField(help_text=b'The name of the puzzle as it will be seen by hunt participants', max_length=200)),
                ('answer', models.CharField(help_text=b'The answer to the puzzle, not case sensitive', max_length=100)),
                ('template', models.TextField(default=b'', help_text=b'The template string to be rendered to HTML on the hunt page')),
                ('resource_link', models.URLField(blank=True, help_text=b'The full link (needs http://) to a folder of additional resources.')),
                ('hunt', models.OneToOneField(help_text=b'The hunt that this puzzle is a part of', on_delete=django.db.models.deletion.CASCADE, to='huntserver.Hunt')),
            ],
        ),
    ]
