# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-08 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0028_prepuzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepuzzle',
            name='response_string',
            field=models.TextField(default=b'', help_text=b'Data returned to the webpage for use upon solving.'),
        ),
        migrations.AlterField(
            model_name='prepuzzle',
            name='hunt',
            field=models.OneToOneField(blank=True, help_text=b'The hunt that this puzzle is a part of', null=True, on_delete=django.db.models.deletion.CASCADE, to='huntserver.Hunt'),
        ),
    ]
