# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0032_auto_20190110_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='extra_data',
            field=models.CharField(blank=True, help_text=b'A misc. field for any extra data to be stored with the hunt.', max_length=200),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='extra_data',
            field=models.CharField(blank=True, help_text=b'A misc. field for any extra data to be stored with the puzzle.', max_length=200),
        ),
    ]
