# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-18 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0033_auto_20190117_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution_link',
            field=models.URLField(blank=True, help_text=b'The full link (needs http://) to a publicly accessible PDF of the solution'),
        ),
    ]
