# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-09 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0034_puzzle_solution_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='resource_link',
            field=models.URLField(blank=True, help_text=b'The full link (needs http://) to a folder of additional resources.'),
        ),
    ]
