# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-10 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0035_hunt_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='last_received_message',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='last_seen_message',
            field=models.IntegerField(default=0),
        ),
    ]
