# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-09-25 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0036_auto_20190310_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_id',
            field=models.CharField(help_text=b'A 3-5 character hex string that uniquely identifies the puzzle', max_length=8, unique=True),
        ),
    ]
