# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-08 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0039_auto_20200108_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='response_time',
            field=models.DateTimeField(blank=True, help_text=b'Hint response time', null=True),
        ),
    ]
