# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-10 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0040_auto_20200108_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='hint_lockout',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='team',
            name='num_available_hints',
            field=models.IntegerField(default=0),
        ),
    ]
