# Generated by Django 2.2 on 2020-02-07 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0043_puzzle_doesnt_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hintunlockplan',
            name='num_triggered',
            field=models.IntegerField(default=0, help_text='Number of times this Unlock Plan has given a hint'),
        ),
    ]
