# Generated by Django 2.2 on 2020-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0044_auto_20200207_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='points_cost',
            field=models.IntegerField(default=0, help_text='The number of points needed to unlock this puzzle.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='points_value',
            field=models.IntegerField(default=0, help_text='The number of points this puzzle grants upon solving.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='unlock_type',
            field=models.CharField(choices=[('TIM', 'Points Based Unlock'), ('SOL', 'Solves Based Unlock'), ('ETH', 'Either Unlocking Method'), ('BTH', 'Both Unlocking Methods')], default='SOL', help_text='The type of puzzle unlocking scheme', max_length=3),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='is_meta',
            field=models.BooleanField(default=False, help_text='Is this puzzle a meta-puzzle?', verbose_name='Is a metapuzzle'),
        ),
    ]
