# Generated by Django 2.2 on 2020-02-09 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0045_auto_20200209_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='last_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The last time that the periodic update management command was ran'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='points_per_minute',
            field=models.IntegerField(default=0, help_text='The number of points granted per minute during the hunt'),
        ),
        migrations.AddField(
            model_name='team',
            name='num_unlock_points',
            field=models.IntegerField(default=0, help_text='The number of points the team has earned'),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='hint_lockout',
            field=models.IntegerField(default=60, help_text='The number of minutes before a hint can be used on a newly unlocked puzzle'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='unlock_type',
            field=models.CharField(choices=[('SOL', 'Solves Based Unlock'), ('POT', 'Points Based Unlock'), ('ETH', 'Either (OR) Unlocking Method'), ('BTH', 'Both (AND) Unlocking Methods')], default='SOL', help_text='The type of puzzle unlocking scheme', max_length=3),
        ),
        migrations.AlterField(
            model_name='team',
            name='num_available_hints',
            field=models.IntegerField(default=0, help_text='The number of hints the team has available to use'),
        ),
    ]
