# Generated by Django 2.2 on 2020-02-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0046_auto_20200209_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='points_cost',
            field=models.IntegerField(default=0, help_text='The number of points needed to unlock this puzzle.'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='points_value',
            field=models.IntegerField(default=0, help_text='The number of points this puzzle grants upon solving.'),
        ),
    ]
