# Generated by Django 2.2 on 2020-02-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0047_auto_20200210_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hint',
            name='request',
            field=models.TextField(help_text='The text of the request for the hint', max_length=1000),
        ),
        migrations.AlterField(
            model_name='hint',
            name='response',
            field=models.TextField(blank=True, help_text='The text of the response to the hint request', max_length=1000),
        ),
    ]
