# Generated by Django 2.2 on 2020-03-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0049_auto_20200215_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='hunt_number',
            field=models.IntegerField(db_index=True, help_text='A number used internally for hunt sorting, must be unique', unique=True),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_id',
            field=models.CharField(db_index=True, help_text='A 3-5 character hex string that uniquely identifies the puzzle', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_received_message',
            field=models.IntegerField(default=0, help_text='The PK of the last message the team has received'),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_seen_message',
            field=models.IntegerField(default=0, help_text='The PK of the last message the team has seen'),
        ),
    ]
