# Generated by Django 2.2 on 2020-03-05 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0050_auto_20200305_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='last_update_time',
        ),
    ]
