# Generated by Django 2.2 on 2020-03-06 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0051_remove_hunt_last_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='num_pages',
        ),
    ]
