# Generated by Django 2.2 on 2020-03-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0052_remove_puzzle_num_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='playtest_end_date',
            field=models.DateTimeField(blank=True, help_text='The date/time at which a hunt will no longer be available to playtesters', null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='playtest_start_date',
            field=models.DateTimeField(blank=True, help_text='The date/time at which a hunt will become to the playtesters', null=True),
        ),
    ]
