# Generated by Django 2.2 on 2020-03-19 01:45

from django.db import migrations
from django.template.loader import get_template


def setup_pages(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    Site = apps.get_model('sites', 'Site')

    source = get_template("contact_us.html").template.source.split("</readme> -->")[1]
    fp = FlatPage.objects.create(url='/contact-us/', title='Contact Us', content=source)
    fp.sites.add(Site.objects.get(pk=1))

    source = get_template("resources.html").template.source.split("</readme> -->")[1]
    fp = FlatPage.objects.create(url='/extra/resources/', title='Resources', content=source)
    fp.sites.add(Site.objects.get(pk=1))

    source = get_template("hunt_info.html").template.source.split("</readme> -->")[1]
    fp = FlatPage.objects.create(url='/hunt-info/', title='Current Hunt Info', content=source)
    fp.sites.add(Site.objects.get(pk=1))
    return


def remove_pages(apps, schema_editor):
    FlatPage = apps.get_model('flatpages', 'FlatPage')
    FlatPage.objects.filter(url='/contact-us/').delete()
    FlatPage.objects.filter(url='/extra/resources/').delete()
    FlatPage.objects.filter(url='/hunt-info/').delete()
    return


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0053_auto_20200310_1503'),
        ('flatpages', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(setup_pages, remove_pages)
    ]
