# Generated by Django 2.2 on 2020-03-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('huntserver', '0054_auto_20200318_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPageProxyObject',
            fields=[
            ],
            options={
                'verbose_name': 'info page',
                'verbose_name_plural': 'info pages',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flatpages.flatpage',),
        ),
    ]
