# Generated by Django 2.2 on 2020-04-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0055_flatpageproxyobject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userproxyobject',
            options={'ordering': ['-pk'], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
