# Generated by Django 2.2.11 on 2020-10-12 01:42

from django.db import migrations, models


def set_defaults(apps, schema_editor):
    Puzzle = apps.get_model('huntserver', 'Puzzle')
    for puzzle in Puzzle.objects.all().iterator():
        if(puzzle.is_html_puzzle):
            puzzle.puzzle_page_type = 'LNK'
        else:
            puzzle.puzzle_page_type = 'PDF'
        puzzle.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0058_auto_20200507_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_page_type',
            field=models.CharField(choices=[('PDF', 'Puzzle page displays a PDF'), ('LNK', 'Puzzle page links a webpage'), ('WEB', 'Puzzle page displays a webpage')], null=True, help_text='The type of webpage for this puzzle.', max_length=3),
        ),
        migrations.RunPython(set_defaults, reverse_func),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_page_type',
            field=models.CharField(choices=[('PDF', 'Puzzle page displays a PDF'), ('LNK', 'Puzzle page links a webpage'), ('WEB', 'Puzzle page displays a webpage')], default='WEB', help_text='The type of webpage for this puzzle.', max_length=3),
        ),
    ]
