# Generated by Django 2.2.11 on 2020-10-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0059_puzzle_puzzle_page_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='is_html_puzzle',
        ),
    ]
