# Generated by Django 2.2.11 on 2020-10-12 14:11

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0060_remove_puzzle_is_html_puzzle'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_file',
            field=models.FileField(blank=True, storage=huntserver.models.OverwriteStorage, upload_to=huntserver.models.get_puzzle_file_path),
        ),
    ]
