# Generated by Django 2.2.11 on 2020-10-12 14:18

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0061_puzzle_puzzle_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_file',
            field=models.FileField(blank=True, storage=huntserver.models.OverwriteStorage(), upload_to=huntserver.models.get_puzzle_file_path),
        ),
    ]
