# Generated by Django 2.2.11 on 2020-10-21 01:51

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0063_auto_20201012_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='link',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_file',
            field=models.FileField(blank=True, storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_puzzle_file_path),
        ),
    ]
