# Generated by Django 2.2.11 on 2020-10-21 02:00

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0064_auto_20201020_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Puzzle resources, MUST BE A ZIP FILE.', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_puzzle_file_path),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution_file',
            field=models.FileField(blank=True, help_text='Puzzle solution. MUST BE A PDF.', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_solution_file_path),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_file',
            field=models.FileField(blank=True, help_text='Puzzle file. MUST BE A PDF', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_puzzle_file_path),
        ),
    ]
