# Generated by Django 2.2.11 on 2020-10-21 02:00


from django.db import migrations
from django.conf import settings
from os import path


def set_files(apps, schema_editor):
    puzzle_folder = "puzzles/"
    solution_folder = "solutions/"

    Puzzle = apps.get_model('huntserver', 'Puzzle')
    for puzzle in Puzzle.objects.all().iterator():
        resource_path = puzzle_folder + puzzle.puzzle_id + ".zip"
        if(puzzle.resource_link and path.exists(settings.MEDIA_ROOT + resource_path)):
            puzzle.resource_file = resource_path
            puzzle.save()

        solution_path = solution_folder + puzzle.puzzle_id + "_sol.pdf"
        if(puzzle.solution_link and path.exists(settings.MEDIA_ROOT + solution_path)):
            puzzle.solution_file = solution_path
            puzzle.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0065_auto_20201020_2200'),
    ]

    operations = [
        migrations.RunPython(set_files, reverse_func)
    ]
