# Generated by Django 2.2.11 on 2020-10-21 23:32

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0067_auto_20201020_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Hunt resources, MUST BE A ZIP FILE.', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_prepuzzle_file_path),
        ),
        migrations.AddField(
            model_name='prepuzzle',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Prepuzzle resources, MUST BE A ZIP FILE.', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_prepuzzle_file_path),
        ),
    ]
