# Generated by Django 2.2.11 on 2020-10-21 23:32

from django.db import migrations
from django.conf import settings
from os import path


def set_files(apps, schema_editor):
    hunt_folder = "hunt/"
    prepuzzle_folder = "prepuzzles/"

    Hunt = apps.get_model('huntserver', 'Hunt')
    for hunt in Hunt.objects.all().iterator():
        resource_path = hunt_folder + str(hunt.hunt_number) + ".zip"
        if(hunt.resource_link and path.exists(settings.MEDIA_ROOT + resource_path)):
            hunt.resource_file = resource_path
            hunt.save()

    Prepuzzle = apps.get_model('huntserver', 'Prepuzzle')
    for puzzle in Prepuzzle.objects.all().iterator():
        resource_path = prepuzzle_folder + str(puzzle.pk) + ".zip"
        if(puzzle.resource_link and path.exists(settings.MEDIA_ROOT + resource_path)):
            puzzle.resource_file = resource_path
            puzzle.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0068_auto_20201021_1932'),
    ]

    operations = [
        migrations.RunPython(set_files, reverse_func)
    ]
