# Generated by Django 2.2.11 on 2020-10-22 00:42

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0069_auto_20201021_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='resource_file',
            field=models.FileField(blank=True, help_text='Hunt resources, MUST BE A ZIP FILE.', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_hunt_file_path),
        ),
    ]
