# Generated by Django 2.2.11 on 2020-10-22 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0070_auto_20201021_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='resource_link',
        ),
        migrations.RemoveField(
            model_name='prepuzzle',
            name='resource_link',
        ),
    ]
