# Generated by Django 2.2.11 on 2020-11-03 20:39

from django.db import migrations, models
import huntserver.models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0071_auto_20201021_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solution_is_webpage',
            field=models.BooleanField(default=False, help_text='Is this solution an html webpage?'),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='solution_resource_file',
            field=models.FileField(blank=True, help_text='Puzzle solution resources, MUST BE A ZIP FILE.', storage=huntserver.models.PuzzleOverwriteStorage(), upload_to=huntserver.models.get_solution_file_path),
        ),
    ]
