# Generated by Django 2.2.13 on 2021-02-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0072_auto_20201103_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzle_type',
            field=models.CharField(choices=[('STD', 'A standard puzzle'), ('MET', 'A meta puzzle'), ('NON', 'An unscored puzzle')], default='STD', help_text='The type of puzzle.', max_length=3),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_page_type',
            field=models.CharField(choices=[('PDF', 'Puzzle page displays a PDF'), ('LNK', 'Puzzle page links a webpage'), ('WEB', 'Puzzle page displays a webpage'), ('EMB', 'Puzzle is html embedded in the webpage')], default='WEB', help_text='The type of webpage for this puzzle.', max_length=3),
        ),
    ]
