# Generated by Django 2.2.13 on 2021-02-08 04:04

from django.db import migrations


def set_puzzle_type(apps, schema_editor):
    Puzzle = apps.get_model('huntserver', 'Puzzle')
    for puzzle in Puzzle.objects.all().iterator():
        if(puzzle.is_meta):
            puzzle.puzzle_type = "MET"
        elif(puzzle.doesnt_count):
            puzzle.puzzle_type = "NON"
        else:
            puzzle.puzzle_type = "STD"
        puzzle.save()


def reverse_func(apps, schema_editor):
    pass  # code for reverting migration, if any


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0073_auto_20210207_2300'),
    ]

    operations = [
        migrations.RunPython(set_puzzle_type, reverse_func)
    ]
