# Generated by Django 2.2.13 on 2021-02-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0074_auto_20210207_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='doesnt_count',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='is_meta',
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_type',
            field=models.CharField(choices=[('STD', 'Standard'), ('MET', 'Meta'), ('FIN', 'Final'), ('NON', 'Non-puzzle')], default='STD', help_text='The type of puzzle.', max_length=3),
        ),
    ]
