# Generated by Django 2.2.13 on 2021-02-10 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0075_auto_20210208_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_local',
            field=models.BooleanField(default=False, help_text='Is this team from CMU (or your organization)'),
        ),
    ]
