# Generated by Django 2.2.13 on 2021-03-26 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0076_team_is_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='responder',
            field=models.ForeignKey(blank=True, help_text='Staff member that has claimed the hint.', null=True, on_delete=django.db.models.deletion.CASCADE, to='huntserver.Person'),
        ),
    ]
