# Generated by Django 2.2.13 on 2022-02-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huntserver', '0077_hint_responder'),
    ]

    operations = [
        migrations.AddField(
            model_name='prepuzzle',
            name='answer_validation_type',
            field=models.CharField(choices=[('STR', 'Strict: Only uppercase A-Z'), ('ACA', 'Case sensitive, no spaces'), ('CAS', 'Case sensitive, spaces allowed'), ('ANY', 'Anything: Full unicode, any case')], default='STR', help_text='The type of answer validation used for this puzzle.', max_length=3),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='answer_validation_type',
            field=models.CharField(choices=[('STR', 'Strict: Only uppercase A-Z'), ('ACA', 'Case sensitive, no spaces'), ('CAS', 'Case sensitive, spaces allowed'), ('ANY', 'Anything: Full unicode, any case')], default='STR', help_text='The type of answer validation used for this puzzle.', max_length=3),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='puzzle_page_type',
            field=models.CharField(choices=[('PDF', 'Puzzle page displays a PDF'), ('LNK', 'Puzzle page links a webpage'), ('WEB', 'Puzzle page displays a webpage'), ('EMB', 'Puzzle is html embedded in the webpage')], default='EMB', help_text='The type of webpage for this puzzle.', max_length=3),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solution_is_webpage',
            field=models.BooleanField(default=True, help_text='Is this solution an html webpage?'),
        ),
    ]
